name: Daily Backup
on:
  schedule:
    - cron: "0 2 * * *" # Run at 2 AM daily
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backup
        run: |
          curl -X POST https://pdygxdmtdmzxcaaacfmf.supabase.co/functions/v1/backup-submissions \
            -H "Authorization: Bearer ${{ secrets.VITE_SUPABASE_ANON_KEY }}"